### ISSUE TITLE
calling "SET SESSION wait_timeout = 3600

### ISSUE THREAD

**Issue by mprofi** [netlogix/Netlogix.Neos.AsyncWorkspaceActions#5]
Hi,

we are facing an Issue using Postgres and this Extension:

netlogix/neos-asyncworkspaceactions includes this package netlogix/cli-increasedatabasetimeout 

calling "SET SESSION wait_timeout = 3600;"  But postgres does not have this.  https://stackoverflow.com/questions/56337335/how-to-set-wait-timeout-value-in-postgresql-as-in-mysql

**Comment by paxuclus** [comment]
Hi @mprofi,

can you please try installing `netlogix/neos-asyncworkspaceactions:dev-main` along with `netlogix/cli-increasedatabasetimeout:dev-main`? I added support for postgres in https://github.com/netlogix/Netlogix.Cli.IncreaseDatabaseTimeout/pull/2, although I did not test it.

The AsyncWorkspaceActions package is currently missing postgres migrations, could you please add them in a pr?
